import type { Metadata } from "next";
import React from "react";

import "@/app/styles/index.scss";
import { notoSansKr, roboto } from "@/app/styles/modules/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${roboto.variable} ${notoSansKr.variable}`}>{children}</body>
    </html>
  );
}
