import { Box } from "@mui/material";
import type { Metadata } from "next";
import React from "react";

import "@/app/styles/index.scss";
import { notoSansKr, roboto } from "@/app/styles/modules/font";
import { Footer, Header } from "@/widgets/Layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <div id="wrapper" className={`${roboto.variable} ${notoSansKr.variable}`}>
          <Header />
          <Box minHeight="100%" margin="-70px 0 -40px" padding="70px 0 40px">
            {children}
          </Box>
          <Footer />
        </div>
      </body>
    </html>
  );
}
