import { Box } from "@mui/material";
import type { Metadata } from "next";
import React from "react";

import "@/app/styles/index.scss";
import { Footer, Header } from "@/widgets/Layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div id="wrapper">
      <Header />
      <Box minHeight="100%" margin="-70px 0 -40px" padding="70px 0 40px">
        {children}
      </Box>
      <Footer />
    </div>
  );
}
